{% set name = "svgwrite" %}
{% set version = "1.2.1" %}
{% set sha256 = "72ef66c9fe367989823cb237ab7f012ac809dd3ba76c1b5ebd9aa61580e2e75e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pyparsing >=2.0.1
  run:
    - python
    - pyparsing >=2.0.1

test:
  imports:
    - svgwrite

about:
  home: https://github.com/mozman/svgwrite
  license: MIT 
  license_family: MIT
  license_file: 'LICENSE.TXT'
  summary: 'A Python library to create SVG drawings.'
  description: 'A Python library to create SVG drawings.'
  doc_url: http://svgwrite.readthedocs.io
  dev_url: https://github.com/mozman/svgwrite

extra:
  recipe-maintainers: 
    - jeromekelleher
