travis:
  secure:
    BINSTAR_TOKEN: L2ZA+jhM6tc0iUQvcHWnlR42qLVj77zMv3qOnVrOu3MNFAgodWWw3J55D/kWtOY204syCJqv47LJflp75Yt0/EopK2aPTMo2sfqN2TSpgjIa7K7/s38agXY73PZAT1XExxmHVe7z48s1Dt/tHhYkSf5dzXpxun/ta/W+97WHgKOZTla6/qigBWM0G+EUUab9fPW/Hr2BGD6cSvZ4Csmj9Py6g7cTPpyRPefd3jrIr9/nGDJvKSe00ng7ucSH15Os4xc609fQDWL8LO9yTxhO78DhSeE6AWccIS1WPDa018etg5nrUp7EA1UJzASllA4j+r7888oQ/WCVAAwcHfB/NT87BRp3DY5eHdzX80NCVHzeRfDewNdWXprQOLPKaf1MnHUp162NEQnY0R/4Bt1dQHxTWV63lLEIJoyKIAfnpNMAeOnr5IWi9PBF3iiiOQBKYoSnQSr/fr3O+2IBM6qFWpu9bt9BU9i/fR2JP76rYqrBJNdobcT9oCTVdYjvrBAnVyGKkpBPrvkMsQ5ungF3u6dXOXJVzLeVnymiISg5lHkDYBJaFO6hrxz0c009wibAVa+qCVf4dK+ofRI2lZUzMvqmykAOA4BRpRQJRN/+hgOK4xr/shKTwPPWspdzg3fWmd7b5KiiBbjQd3jIFbAZ4acRrB6eJYT0w32zSyF4KyM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
