travis:
  secure:
    BINSTAR_TOKEN: LnSpgL29ii2Nnmi9Uhg7/7TOm/eJ2FxcKY6xIydxkOksLria8JbqxA3PkuWFLYxRi8qOjF+d7U6tcyTN98tGSb33kOdvHfzUZuTU6exi9O38/0JIJAptz3paQD+9z9rflt1/C8lRTOkBVWhC+F99l4T4CVIJYghQUlD3z21yWZlrSbI6ckfRpMzF14fwUNYLT77soZtQQovkoIsCykeY5lr+3xTdGwbdpuBF89ieDy/asiYczyz+3z4h2XdN9+gAb9TSMZOUci9kjUIRMWkUSM6xf5vw1wT0u6ipGnGjlCeRyOiP3zI8W96Fv5fMoIosCJP2M/l336ZFjesgJOxDnXidrjp8kPnK5Z1oquGlF+sFfGpYgUVKoSA8rnpoS7ou1J1Mzl1XjNxeFa8aAqZ3AduEjsgGFiuc6jd72sOTucSd6UfarbAcR2xEQ4Pn4r9OlORNRNTUlV1URTwo4Uak4RSbqW2c/iB5HG0EcKVD4PH0QVcG0CZHTRj/hNHcjmhG20k/ozmhwM06k3rrx47MKSkBw9+aLb2Yf7OGYTmkKsMq4joe9bZPyOzngkNm055dL1PjBdjzzzziA0cSWQUL2sYFpPRYu/vEMvaVzLjjtGaWBgrlc/oA5Bpo8qO03tIGQUEbUgOnuqJoK8+CDajzafkK3/NFyZMcvgovfQ3+pww=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
